version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: MySQL
    restart: always
    cap_add:
       - SYS_NICE
    environment:
       - MYSQL_DATABASE=${MYSQL_DATABASE}
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
       - mysql-data:/var/lib/mysql
    ports:
       - 5012:3306
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: PhpMyAdmin     
    restart: always
    ports:
       - 5013:80
    environment:
       - PMA_ARBITRARY=1
       
volumes:
   mysql-data: